#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-blankslate
Version  : 3.1.3
Release  : 8
URL      : https://rubygems.org/downloads/blankslate-3.1.3.gem
Source0  : https://rubygems.org/downloads/blankslate-3.1.3.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-devise
BuildRequires : rubygem-diff-lcs
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-rspec
BuildRequires : rubygem-rspec-core
BuildRequires : rubygem-rspec-expectations
BuildRequires : rubygem-rspec-mocks
BuildRequires : rubygem-rspec-support

%description
BlankSlate
===
BlankSlate provides an abstract base class with no predefined
methods (except for <tt>\_\_send__</tt> and <tt>\_\_id__</tt>).
BlankSlate is useful as a base class when writing classes that
depend upon <tt>method_missing</tt> (e.g. dynamic proxies).

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n blankslate-3.1.3
gem spec %{SOURCE0} -l --ruby > rubygem-blankslate.gemspec

%build
gem build rubygem-blankslate.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
blankslate-3.1.3.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
pushd %{buildroot}%{gem_dir}/gems/blankslate-3.1.3
rspec -I.:lib spec/
popd


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/blankslate-3.1.3.gem
/usr/lib64/ruby/gems/2.3.0/gems/blankslate-3.1.3/Gemfile
/usr/lib64/ruby/gems/2.3.0/gems/blankslate-3.1.3/Gemfile.lock
/usr/lib64/ruby/gems/2.3.0/gems/blankslate-3.1.3/MIT-LICENSE
/usr/lib64/ruby/gems/2.3.0/gems/blankslate-3.1.3/README
/usr/lib64/ruby/gems/2.3.0/gems/blankslate-3.1.3/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/blankslate-3.1.3/VERSION
/usr/lib64/ruby/gems/2.3.0/gems/blankslate-3.1.3/blankslate.gemspec
/usr/lib64/ruby/gems/2.3.0/gems/blankslate-3.1.3/lib/blankslate.rb
/usr/lib64/ruby/gems/2.3.0/gems/blankslate-3.1.3/spec/blankslate_spec.rb
/usr/lib64/ruby/gems/2.3.0/specifications/blankslate-3.1.3.gemspec
